### ISSUE TITLE
database is missing and error

### ISSUE THREAD

**Issue by rizkychimo** [kunal047/Steganography#1]
can i have database sir??

i have an error like this

C:\xampp\htdocs\server>python app.py
  File "app.py", line 89
    print "this is here.."
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "t
his is here..")?

can i get fix it sir??
thanks for your project

**Comment by kunal047** [comment]
There is no need for database. That error is because you are using Python 2 instead use Python 3 to solve that error.
